dist: bionic
language: java

jobs:
  include:
    - stage: compile
      script: mvn compile
    - stage: test
      script: mvn test
    - stage: deploy
      deploy:
        provider: script
        script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy
        cleanup: false
        skip_cleanup: true
        on:
          tags: true