main: be.renaud11232.plugins.awesomecommands.AwesomePlugin
name: AwesomePlugin
version: ${version}
commands:
    foo:
        description: Foo desc
        usage: /<command>
        permission: complex.foo
        subcommands:
            foobar:
                description: Foobar desc
                permission: complex.foo.bar
                aliases:
                    - fb
                    - foba
    bar:
        description: Bar desc
        usage: /<command>
        permission: complex.bar
        aliases: aliasbar