name: Build
on:
  release:
    types:
      - released
      - prereleased
  push:
jobs:
  build:
    name: Build jar artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt
      - name: Build jar
        run: mvn package
      - name: Upload built jar
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: target/*.jar
  build-javadoc:
    name: Build javadoc
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt
      - name: Build javadoc
        run: mvn javadoc:javadoc
      - name: Upload built javadoc
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: target/site/apidocs/
  deploy-javadoc:
    name: Deploy javadoc to GitHub pages
    needs: build-javadoc
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download built javadoc
        uses: actions/download-artifact@v3
        with:
          name: javadoc
          path: target/site/apidocs/
      - name: Disables jekyll
        run: touch target/site/apidocs/.nojekyll
      - name: Publish on GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: target/site/apidocs
          clean: true
  deploy-gh-release:
    name: Attach built jar on GH release
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download built jar
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: target/
      - name: Upload on GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/*.jar
  deploy-gh-packages:
    name: Deploy on GitHub Packages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

